;;
;; Deovi client package
;;
[metadata]
name = deovi
version = 1.0.0
description = Tools to rename files, collect their filepaths and scrap information from TMDB
long_description = file:README.rst
long_description_content_type = text/x-rst
author = David Thenon
author_email = sveetch@gmail.com
url = https://github.com/sveetch/deovi
license = MIT
keywords = Python
classifiers =
    Development Status :: 5 - Production/Stable
    Intended Audience :: Developers
    License :: OSI Approved :: MIT License
    Natural Language :: English
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12
    Programming Language :: Python :: 3.13

[options]
include_package_data = True
python_requires = >=3.10
install_requires =
    click>=8.0,<9.0
    colorlog>=6.7.0
    python-slugify[unidecode]>=8.0.1
    PyYAML>=6.0
    deepdiff>=7.0.1
    tmdbv3api>=1.7.7,<2.0.0
    requests>=2.30.0
packages = find:
zip_safe = True

[options.extras_require]
dev =
    pytest>=7.0
    freezegun>=1.2.0
quality =
    flake8>=6.0.0
    tox>=4.11.0
doc =
    sphinx>=8.0.2
    furo>=2024.8.6
    sphinx-copybutton>=0.5.2
doc-live =
    livereload>=2.6.0
release =
    twine>=5.0.0

[options.packages.find]
where = .
exclude=
    data
    docs
    tests

[options.entry_points]
console_scripts =
    deovi = deovi.cli.entrypoint:cli_frontend

[wheel]
universal = 0

;;
;; Third-party packages configuration
;;
[flake8]
max-line-length = 88
exclude =
    .git,
    .venv,
    build,
    __pycache__

[tool:pytest]
addopts = -v --tb=long
python_files =
    *.py
testpaths =
    tests

[tox:tox]
minversion = 3.4.0
envlist =  py{310,312,313}

[testenv]

commands =
    pip install -e .[dev]
    pytest -vv tests
